#!/bin/bash

echo "Branch name: $TRAVIS_PULL_REQUEST_BRANCH"

if [[ "$TRAVIS_PULL_REQUEST_BRANCH" == 'master' ]]; then
    exit 0
fi

for PREFIX in feature bugfix hotfix release; do
    if [[ "$TRAVIS_PULL_REQUEST_BRANCH" == $PREFIX/* ]]; then
        exit 0
    fi
    for CODE in app lib; do
        if [[ "$TRAVIS_PULL_REQUEST_BRANCH" == $CODE/$PREFIX/* ]]; then
            exit 0
        fi
    done
done

echo "Branch name does not pass convention."
exit 1
